### ISSUE TITLE
iOS无需越狱在线安装ipa，一键上传ipa，开源代码，自部署应用分发服务，类似fir.im | Steven Jobs's Blog

### ISSUE THREAD

**Issue by iineva** [iineva/iineva.github.io#2]
https://ineva.cn/2017/12/22/iOS-ipa-Server/

**Comment by JoeJoeLam** [comment]
关于启动caddy反向代理这块不太懂，楼主是在代码中包含了caddy的模块吗，没太看懂呢

**Comment by iineva** [comment]
代码中不包含 caddy 的代码，也没必要包含。这里配置的 https 网关是另外一个独立进程，网关的作用是处理 https 请求。可以使用任意 https 网关来代替 caddy，如 nginx 等。这里使用 caddy 的原因是因为 caddy 比较容易配置，并且能自动申请 https 证书。
